/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-04 04:23:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Cozima_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.13.0/css/all.css\" integrity=\"sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&family=Karla&family=Oswald&family=Roboto:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Cozima.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<title>Cozima Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hello -->\r\n");
      out.write("  <div class=\"p-banner\" id=\"section_Hello\">\r\n");
      out.write("    <h2 class=\"banner-text\">Cada refeição é um mistério <br> por saborear</h2>\r\n");
      out.write("    <div class=\"text-underline\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container_intro\">\r\n");
      out.write("    <section class=\"section_intro\">\r\n");
      out.write("        <div class=\"contents-img\" ><img src=\"images/chefs.jpg\" width=\"350px\"></div>\r\n");
      out.write("        <div class=\"contents-text\">\r\n");
      out.write("            <h4>“Imagination is more important than knowledge.” <br>\r\n");
      out.write("                – Albert Einstein –</h4>\r\n");
      out.write("            <p>Borne by the water surrounding South America to the sweeping waves \r\n");
      out.write("            of the Mediterranean sea hitting the shores of the Maltese Islands,<br> \r\n");
      out.write("            Susurrus presents an exciting Mediterranean cuisine influenced by the diversity of South American food,<br>\r\n");
      out.write("            bonded with fresh local ingredients and avant-garde techniques bestowing a novel dining escapade.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Menu-->\r\n");
      out.write("  <div class=\"p-banner\" id=\"section_Menu\">\r\n");
      out.write("    <h2 class=\"banner-text\">Menu</h2>\r\n");
      out.write("    <div class=\"text-underline\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"eat-section\">\r\n");
      out.write("    <input id=\"main_menu\" type=\"radio\" name=\"sub_nav\" checked=\"checked\">\r\n");
      out.write("    <input id=\"side_menu\" type=\"radio\" name=\"sub_nav\">\r\n");
      out.write("    <input id=\"drink\" type=\"radio\" name=\"sub_nav\">\r\n");
      out.write("    <div class=\"eat-menu\">\r\n");
      out.write("        <div >\r\n");
      out.write("            <label class=\"eat-menu-label\" for=\"main_menu\">Main menu</label>\r\n");
      out.write("            <label class=\"eat-menu-label\" for=\"side_menu\">Side menu</label>\r\n");
      out.write("            <label class=\"eat-menu-label\" for=\"drink\">Drink</label>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"eat-submenu\">    \r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("                <p>Mari</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>salmon trufado</p>\r\n");
      out.write("                <p>pork,liquorice</p>\r\n");
      out.write("                <p>bacon crispy gyozas</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("                <p>KRW 18,500</p>\r\n");
      out.write("                <p>KRW 18,500</p>\r\n");
      out.write("                <p>KRW 19,000</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("                <p>beef</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>taco</p>\r\n");
      out.write("                <p>pisconito </p>\r\n");
      out.write("                <p>lacal bass</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("                <p>KRW 26,500</p>\r\n");
      out.write("                <p>KRW 38,500</p>\r\n");
      out.write("                <p>KRW 58,500</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("                <p>Rice</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>boneless imperial duck</p>\r\n");
      out.write("                <p>pork on grill</p>\r\n");
      out.write("                <p>boneless premium</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("                <p>KRW 18,500</p>\r\n");
      out.write("                <p>KRW 38,000</p>\r\n");
      out.write("                <p>KRW 38,500</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("                <p>Noodle</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("              <p>asian noodle</p>\r\n");
      out.write("              <p>noodle fry</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("              <p>KRW 8,500</p>\r\n");
      out.write("              <p>KRW 8,500</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"eat-submenu\">\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("              <p>Side</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>seabass</p>\r\n");
      out.write("                <p>peking duck</p>\r\n");
      out.write("                <p>blue tiger prawns tempura</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("              <p>KRW 20,000</p>\r\n");
      out.write("              <p>KRW 20,000</p>\r\n");
      out.write("              <p>KRW 40,000</p>              \r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("              <p>Other</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>rabbit taco</p>\r\n");
      out.write("                <p>sea meagre</p>\r\n");
      out.write("                <p>sea meagre vegan</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("              <p>KRW 8,500</p>\r\n");
      out.write("              <p>KRW 13,000</p>\r\n");
      out.write("              <p>KRW 20,500</p>              \r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"eat-submenu\">\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"sub_title\">\r\n");
      out.write("              <p>Beverage</p>\r\n");
      out.write("                <div class=\"my-line\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-name\">\r\n");
      out.write("                <p>grambeira</p>\r\n");
      out.write("                <p>planalto</p>\r\n");
      out.write("                <p>pomares</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-price\">\r\n");
      out.write("              <p>KRW 18,500</p>\r\n");
      out.write("              <p>KRW 23,000</p>\r\n");
      out.write("              <p>KRW 30,000</p>              \r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Gallery -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "gallery.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Contact -->\r\n");
      out.write("  <div class=\"p-banner\" id=\"section_Contact\">\r\n");
      out.write("    <h2 class=\"banner-text\">Contact</h2>\r\n");
      out.write("    <div class=\"text-underline\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container_Contact\">\r\n");
      out.write("    <section class=\"section_Contact\">\r\n");
      out.write("      <div id=\"location_text\">\r\n");
      out.write("          <div class=\"text_block\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                  <li><h4>ADDRESS</h4></li>\r\n");
      out.write("                  <li><p>서울시 강남구 <br> 논현로 76길 27 2층</p></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text_block\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><h4>FREE PARKING</h4></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text_block\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><h4>OPENING HOURS</h4></li>\r\n");
      out.write("                <li><p>Mon To Sun <br> 10:00 to 22:00</p></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text_block\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li><h4>CONTACT NUMBER</h4></li>\r\n");
      out.write("                <li><P>02-515-9657</P></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"map\">\r\n");
      out.write("        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3166.2426812030712!2d126.88296601564527!3d37.47859917981453!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.\r\n");
      out.write("        1!3m3!1m2!1s0x357b61e1915f6d57%3A0x9bafbfdb92b0d448!2z7Iqk7L-o7ZG465Oc66eI66as7Jik7JWE7Jq466Cb7KCQ!5e0!3m2!1sko!2skr!4v1591777738572!5m2!1sko!2skr\" \r\n");
      out.write("        width=\"650\" height=\"450\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"p-banner\" id=\"section_Reservation\">\r\n");
      out.write("    <h2 class=\"banner-text\">Reservation</h2>\r\n");
      out.write("    <div class=\"text-underline\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("<!-- Reservation -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "resFrm.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!-- Footer -->  \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/test.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
